stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: radar/app:v1
      pushRemote: true
      registry: a8ree.azurecr.io
timeout: 60
notification: {}
